apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterprofile-provider-file
  namespace: system
data:
  config.json: |
    {
      "providers": [
        {
          "name": "open-cluster-management",
          "execConfig": {
            "apiVersion": "client.authentication.k8s.io/v1",
            "command": "/plugins/cp-creds",
            "args": ["--managed-serviceaccount=aws-workload-identity-operator"],
            "provideClusterInfo": true,
            "interactiveMode": "Never"
          }
        },
        {
          "name": "secretreader",
          "execConfig": {
            "apiVersion": "client.authentication.k8s.io/v1",
            "command": "/plugins/secretreader/bin/secretreader-plugin",
            "provideClusterInfo": true,
            "interactiveMode": "Never"
          }
        },
        {
          "name": "kubeconfig-secretreader",
          "execConfig": {
            "apiVersion": "client.authentication.k8s.io/v1",
            "command": "/plugins/kubeconfig-secretreader/bin/kubeconfig-secretreader-plugin",
            "provideClusterInfo": true,
            "interactiveMode": "Never"
          }
        }
      ]
    }
