{{- if .Values.serviceMonitor.enabled }}
{{- $namespace := include "awio.namespace" . }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "awio.fullname" . }}
  namespace: {{ default $namespace .Values.serviceMonitor.namespace }}
  labels:
    {{- include "awio.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with merge .Values.serviceMonitor.annotations .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "awio.selectorLabels" . | nindent 6 }}
  {{- if .Values.serviceMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml .Values.serviceMonitor.namespaceSelector | nindent 4 }}
  {{- else if and .Values.serviceMonitor.namespace (ne .Values.serviceMonitor.namespace $namespace) }}
  namespaceSelector:
    matchNames:
      - {{ $namespace | quote }}
  {{- end }}
  endpoints:
    - port: metrics
      path: {{ .Values.serviceMonitor.path | quote }}
      scheme: {{ .Values.serviceMonitor.scheme | quote }}
      interval: {{ .Values.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | quote }}
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      {{- if .Values.serviceMonitor.authorization }}
      authorization:
        {{- toYaml .Values.serviceMonitor.authorization | nindent 8 }}
      {{- else if .Values.serviceMonitor.bearerTokenFile }}
      bearerTokenFile: {{ .Values.serviceMonitor.bearerTokenFile | quote }}
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
