// Package aws builds AWS ACK resources.
package aws

import (
	"bytes"
	"encoding/json"
	"fmt"
	"maps"
	"slices"
	"unicode/utf8"

	eksv1alpha1 "github.com/aws-controllers-k8s/eks-controller/apis/v1alpha1"
	iamv1alpha1 "github.com/aws-controllers-k8s/iam-controller/apis/v1alpha1"
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	s3v1alpha1 "github.com/aws-controllers-k8s/s3-controller/apis/v1alpha1"
	"github.com/aws/aws-sdk-go-v2/aws"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"

	identityv1 "github.com/appthrust/aws-workload-identity-operator/api/v1alpha1"
	"github.com/appthrust/aws-workload-identity-operator/pkg/remoteirsa"
)

// EKSPodIdentityServicePrincipal is the AWS service principal that EKS Pod
// Identity uses when assuming generated workload roles.
const EKSPodIdentityServicePrincipal = "pods.eks.amazonaws.com"

// EKSIdentity contains EKS cluster identity used by Pod Identity resources.
type EKSIdentity struct {
	ClusterName       string
	ClusterARN        string
	AWSOrganizationID string
}

// BuildIAMPolicy renders the ACK IAM Policy child resource for a role.
func BuildIAMPolicy(role *identityv1.AWSServiceAccountRole, delivery identityv1.DeliveryType, policyDocument string) *iamv1alpha1.Policy {
	name := PolicyName(role)
	labels := LabelsForRole(role, delivery)

	return &iamv1alpha1.Policy{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: role.Namespace, Labels: labels},
		Spec: iamv1alpha1.PolicySpec{
			Name:           aws.String(name),
			Description:    aws.String("Generated by aws-workload-identity-operator for " + role.Namespace + "/" + role.Name),
			PolicyDocument: aws.String(policyDocument),
			Tags:           iamTags(labels),
		},
	}
}

// BuildIAMRole renders the ACK IAM Role child resource for a workload role.
func BuildIAMRole(role *identityv1.AWSServiceAccountRole, delivery identityv1.DeliveryType, boundaryARN, trustPolicy string, policyARNs []string) *iamv1alpha1.Role {
	name := RoleName(role)
	labels := LabelsForRole(role, delivery)

	spec := iamv1alpha1.RoleSpec{
		Name:                     aws.String(name),
		AssumeRolePolicyDocument: aws.String(trustPolicy),
		MaxSessionDuration:       aws.Int64(3600),
		Path:                     aws.String("/"),
		Policies:                 aws.StringSlice(policyARNs),
		Tags:                     iamTags(labels),
	}
	if boundaryARN != "" {
		spec.PermissionsBoundary = aws.String(boundaryARN)
	}

	return &iamv1alpha1.Role{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: role.Namespace, Labels: labels},
		Spec:       spec,
	}
}

// BuildOIDCProvider renders the ACK IAM OIDC provider for a namespace config.
func BuildOIDCProvider(config *identityv1.AWSWorkloadIdentityConfig) *iamv1alpha1.OpenIDConnectProvider {
	labels := LabelsForConfig(config)

	return &iamv1alpha1.OpenIDConnectProvider{
		ObjectMeta: metav1.ObjectMeta{Name: OIDCProviderName(config), Namespace: config.Namespace, Labels: labels},
		Spec: iamv1alpha1.OpenIDConnectProviderSpec{
			URL:       aws.String(config.Status.IssuerURL()),
			ClientIDs: aws.StringSlice([]string{remoteirsa.STSAudience}),
			Tags:      iamTags(labels),
		},
	}
}

// BuildBucket renders the ACK S3 Bucket for the self-hosted issuer.
func BuildBucket(config *identityv1.AWSWorkloadIdentityConfig) (*s3v1alpha1.Bucket, error) {
	name := ""
	if config.Status.SelfHostedIssuer != nil {
		name = config.Status.SelfHostedIssuer.BucketName
	}

	if name == "" {
		name = BucketName(config.Namespace, config.Spec.Region)
	}

	labels := LabelsForConfig(config)

	policy, err := BucketPolicy(name)
	if err != nil {
		return nil, fmt.Errorf("build bucket policy: %w", err)
	}

	return &s3v1alpha1.Bucket{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: config.Namespace, Labels: labels},
		Spec: s3v1alpha1.BucketSpec{
			Name:            aws.String(name),
			ObjectOwnership: aws.String("BucketOwnerEnforced"),
			Policy:          aws.String(policy),
			PublicAccessBlock: &s3v1alpha1.PublicAccessBlockConfiguration{
				BlockPublicACLs:       aws.Bool(true),
				BlockPublicPolicy:     aws.Bool(false),
				IgnorePublicACLs:      aws.Bool(true),
				RestrictPublicBuckets: aws.Bool(false),
			},
			Tagging: s3Tagging(labels),
		},
	}, nil
}

// BuildPodIdentityAssociation renders the ACK EKS PodIdentityAssociation.
func BuildPodIdentityAssociation(role *identityv1.AWSServiceAccountRole, roleARN string, eks EKSIdentity) *eksv1alpha1.PodIdentityAssociation {
	labels := LabelsForRole(role, identityv1.DeliveryTypeEKSPodIdentity)

	return &eksv1alpha1.PodIdentityAssociation{
		ObjectMeta: metav1.ObjectMeta{Name: PodIdentityAssociationName(role), Namespace: role.Namespace, Labels: labels},
		Spec: eksv1alpha1.PodIdentityAssociationSpec{
			ClientRequestToken: aws.String(string(role.UID)),
			ClusterName:        aws.String(eks.ClusterName),
			Namespace:          aws.String(role.Spec.ServiceAccount.Namespace),
			ServiceAccount:     aws.String(role.Spec.ServiceAccount.Name),
			RoleARN:            aws.String(roleARN),
			Tags:               aws.StringMap(labels),
		},
	}
}

// IsACKSynced reports whether ACK marked a resource as synced.
func IsACKSynced(conditions []*ackv1alpha1.Condition) bool {
	for _, cond := range conditions {
		if cond != nil && cond.Type == ackv1alpha1.ConditionTypeResourceSynced && cond.Status == corev1.ConditionTrue {
			return true
		}
	}

	return false
}

// ACKResourceStatus copies ACK child identity and conditions into parent status.
func ACKResourceStatus(apiVersion, kind string, obj metav1.Object, conditions []*ackv1alpha1.Condition) identityv1.ACKResourceStatus {
	return identityv1.ACKResourceStatus{
		APIVersion: apiVersion,
		Kind:       kind,
		Namespace:  obj.GetNamespace(),
		Name:       obj.GetName(),
		Conditions: ackConditions(conditions),
	}
}

func ackConditions(conditions []*ackv1alpha1.Condition) []identityv1.ACKResourceCondition {
	out := make([]identityv1.ACKResourceCondition, 0, len(conditions))

	for _, cond := range conditions {
		if cond == nil {
			continue
		}

		out = append(out, identityv1.ACKResourceCondition{
			Type:               string(cond.Type),
			Status:             cond.Status,
			LastTransitionTime: cond.LastTransitionTime,
			Reason:             aws.ToString(cond.Reason),
			Message:            aws.ToString(cond.Message),
		})
	}

	if len(out) == 0 {
		return nil
	}

	return out
}

// ARN extracts an ACK resource ARN from metadata.
func ARN(metadata *ackv1alpha1.ResourceMetadata) string {
	if metadata == nil {
		return ""
	}

	return aws.ToString((*string)(metadata.ARN))
}

// sortedTags returns labels as a deterministic slice of provider-specific tag
// objects. Sorting keeps Update diffs stable across reconciles.
func sortedTags[T any](labels map[string]string, mk func(key, value string) T) []T {
	out := make([]T, 0, len(labels))
	for _, key := range slices.Sorted(maps.Keys(labels)) {
		out = append(out, mk(key, labels[key]))
	}

	return out
}

func iamTags(labels map[string]string) []*iamv1alpha1.Tag {
	return sortedTags(labels, func(key, value string) *iamv1alpha1.Tag {
		return &iamv1alpha1.Tag{Key: aws.String(key), Value: aws.String(value)}
	})
}

func s3Tagging(labels map[string]string) *s3v1alpha1.Tagging {
	return &s3v1alpha1.Tagging{TagSet: sortedTags(labels, func(key, value string) *s3v1alpha1.Tag {
		return &s3v1alpha1.Tag{Key: aws.String(key), Value: aws.String(value)}
	})}
}

// PolicyDocumentString serializes the inline IAM policy document to compact
// JSON for forwarding to AWS IAM. Keep string conversion here at the ACK/AWS
// boundary: the public API intentionally stores policyDocument as an object so
// Kubernetes rejects non-object input before reconcile and YAML formatting does
// not become part of the user contract. AWS IAM remains the final authority on
// policy semantics.
func PolicyDocumentString(doc *runtime.RawExtension) (string, error) {
	if doc == nil || (len(doc.Raw) == 0 && doc.Object == nil) {
		return "", fmt.Errorf("policy document is empty")
	}

	raw := doc.Raw
	if len(raw) == 0 && doc.Object != nil {
		var err error
		raw, err = json.Marshal(doc.Object)
		if err != nil {
			return "", fmt.Errorf("serialize policy document: %w", err)
		}
	}

	var probe map[string]any
	if err := json.Unmarshal(raw, &probe); err != nil {
		return "", fmt.Errorf("parse policy document: %w", err)
	}
	if len(probe) == 0 {
		return "", fmt.Errorf("policy document is empty")
	}

	var compact bytes.Buffer
	if err := json.Compact(&compact, raw); err != nil {
		return "", fmt.Errorf("compact policy document: %w", err)
	}
	if utf8.RuneCount(compact.Bytes()) > 6144 {
		return "", fmt.Errorf("policy document exceeds AWS IAM customer-managed policy size limit of 6144 characters")
	}

	return compact.String(), nil
}
