//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACKResourceCondition) DeepCopyInto(out *ACKResourceCondition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACKResourceCondition.
func (in *ACKResourceCondition) DeepCopy() *ACKResourceCondition {
	if in == nil {
		return nil
	}
	out := new(ACKResourceCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACKResourceStatus) DeepCopyInto(out *ACKResourceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ACKResourceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACKResourceStatus.
func (in *ACKResourceStatus) DeepCopy() *ACKResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ACKResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRole) DeepCopyInto(out *AWSServiceAccountRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRole.
func (in *AWSServiceAccountRole) DeepCopy() *AWSServiceAccountRole {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSServiceAccountRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleList) DeepCopyInto(out *AWSServiceAccountRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSServiceAccountRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleList.
func (in *AWSServiceAccountRoleList) DeepCopy() *AWSServiceAccountRoleList {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSServiceAccountRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleSpec) DeepCopyInto(out *AWSServiceAccountRoleSpec) {
	*out = *in
	out.ServiceAccount = in.ServiceAccount
	if in.PolicyARNs != nil {
		in, out := &in.PolicyARNs, &out.PolicyARNs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicyDocument != nil {
		in, out := &in.PolicyDocument, &out.PolicyDocument
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleSpec.
func (in *AWSServiceAccountRoleSpec) DeepCopy() *AWSServiceAccountRoleSpec {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleStatus) DeepCopyInto(out *AWSServiceAccountRoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ACKResources != nil {
		in, out := &in.ACKResources, &out.ACKResources
		*out = make([]ACKResourceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleStatus.
func (in *AWSServiceAccountRoleStatus) DeepCopy() *AWSServiceAccountRoleStatus {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityConfig) DeepCopyInto(out *AWSWorkloadIdentityConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityConfig.
func (in *AWSWorkloadIdentityConfig) DeepCopy() *AWSWorkloadIdentityConfig {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSWorkloadIdentityConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityConfigList) DeepCopyInto(out *AWSWorkloadIdentityConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSWorkloadIdentityConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityConfigList.
func (in *AWSWorkloadIdentityConfigList) DeepCopy() *AWSWorkloadIdentityConfigList {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSWorkloadIdentityConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityConfigSpec) DeepCopyInto(out *AWSWorkloadIdentityConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityConfigSpec.
func (in *AWSWorkloadIdentityConfigSpec) DeepCopy() *AWSWorkloadIdentityConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityConfigStatus) DeepCopyInto(out *AWSWorkloadIdentityConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ACKResources != nil {
		in, out := &in.ACKResources, &out.ACKResources
		*out = make([]ACKResourceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WebhookRuntimeCertNotAfter != nil {
		in, out := &in.WebhookRuntimeCertNotAfter, &out.WebhookRuntimeCertNotAfter
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityConfigStatus.
func (in *AWSWorkloadIdentityConfigStatus) DeepCopy() *AWSWorkloadIdentityConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityOperatorConfig) DeepCopyInto(out *AWSWorkloadIdentityOperatorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityOperatorConfig.
func (in *AWSWorkloadIdentityOperatorConfig) DeepCopy() *AWSWorkloadIdentityOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSWorkloadIdentityOperatorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityOperatorConfigList) DeepCopyInto(out *AWSWorkloadIdentityOperatorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSWorkloadIdentityOperatorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityOperatorConfigList.
func (in *AWSWorkloadIdentityOperatorConfigList) DeepCopy() *AWSWorkloadIdentityOperatorConfigList {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityOperatorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSWorkloadIdentityOperatorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityOperatorConfigSpec) DeepCopyInto(out *AWSWorkloadIdentityOperatorConfigSpec) {
	*out = *in
	out.SelfHostedIRSA = in.SelfHostedIRSA
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityOperatorConfigSpec.
func (in *AWSWorkloadIdentityOperatorConfigSpec) DeepCopy() *AWSWorkloadIdentityOperatorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityOperatorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfHostedIRSAConfig) DeepCopyInto(out *SelfHostedIRSAConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfHostedIRSAConfig.
func (in *SelfHostedIRSAConfig) DeepCopy() *SelfHostedIRSAConfig {
	if in == nil {
		return nil
	}
	out := new(SelfHostedIRSAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountSubject) DeepCopyInto(out *ServiceAccountSubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountSubject.
func (in *ServiceAccountSubject) DeepCopy() *ServiceAccountSubject {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountSubject)
	in.DeepCopyInto(out)
	return out
}
