//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACKResourceCondition) DeepCopyInto(out *ACKResourceCondition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACKResourceCondition.
func (in *ACKResourceCondition) DeepCopy() *ACKResourceCondition {
	if in == nil {
		return nil
	}
	out := new(ACKResourceCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACKResourceStatus) DeepCopyInto(out *ACKResourceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ACKResourceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACKResourceStatus.
func (in *ACKResourceStatus) DeepCopy() *ACKResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ACKResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRole) DeepCopyInto(out *AWSServiceAccountRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRole.
func (in *AWSServiceAccountRole) DeepCopy() *AWSServiceAccountRole {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSServiceAccountRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleClusterFailure) DeepCopyInto(out *AWSServiceAccountRoleClusterFailure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleClusterFailure.
func (in *AWSServiceAccountRoleClusterFailure) DeepCopy() *AWSServiceAccountRoleClusterFailure {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleClusterFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleClusterSummary) DeepCopyInto(out *AWSServiceAccountRoleClusterSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleClusterSummary.
func (in *AWSServiceAccountRoleClusterSummary) DeepCopy() *AWSServiceAccountRoleClusterSummary {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleClusterSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleList) DeepCopyInto(out *AWSServiceAccountRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSServiceAccountRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleList.
func (in *AWSServiceAccountRoleList) DeepCopy() *AWSServiceAccountRoleList {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSServiceAccountRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRolePlacementStatus) DeepCopyInto(out *AWSServiceAccountRolePlacementStatus) {
	*out = *in
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(AWSServiceAccountRoleRolloutSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRolePlacementStatus.
func (in *AWSServiceAccountRolePlacementStatus) DeepCopy() *AWSServiceAccountRolePlacementStatus {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRolePlacementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleReplicaSet) DeepCopyInto(out *AWSServiceAccountRoleReplicaSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleReplicaSet.
func (in *AWSServiceAccountRoleReplicaSet) DeepCopy() *AWSServiceAccountRoleReplicaSet {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleReplicaSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSServiceAccountRoleReplicaSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleReplicaSetList) DeepCopyInto(out *AWSServiceAccountRoleReplicaSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSServiceAccountRoleReplicaSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleReplicaSetList.
func (in *AWSServiceAccountRoleReplicaSetList) DeepCopy() *AWSServiceAccountRoleReplicaSetList {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleReplicaSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSServiceAccountRoleReplicaSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleReplicaSetSpec) DeepCopyInto(out *AWSServiceAccountRoleReplicaSetSpec) {
	*out = *in
	if in.PlacementRefs != nil {
		in, out := &in.PlacementRefs, &out.PlacementRefs
		*out = make([]PlacementRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleReplicaSetSpec.
func (in *AWSServiceAccountRoleReplicaSetSpec) DeepCopy() *AWSServiceAccountRoleReplicaSetSpec {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleReplicaSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleReplicaSetStatus) DeepCopyInto(out *AWSServiceAccountRoleReplicaSetStatus) {
	*out = *in
	if in.Placements != nil {
		in, out := &in.Placements, &out.Placements
		*out = make([]AWSServiceAccountRolePlacementStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(AWSServiceAccountRoleRolloutSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.FailedClusters != nil {
		in, out := &in.FailedClusters, &out.FailedClusters
		*out = make([]AWSServiceAccountRoleClusterFailure, len(*in))
		copy(*out, *in)
	}
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]AWSServiceAccountRoleClusterSummary, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleReplicaSetStatus.
func (in *AWSServiceAccountRoleReplicaSetStatus) DeepCopy() *AWSServiceAccountRoleReplicaSetStatus {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleReplicaSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleRolloutSummary) DeepCopyInto(out *AWSServiceAccountRoleRolloutSummary) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleRolloutSummary.
func (in *AWSServiceAccountRoleRolloutSummary) DeepCopy() *AWSServiceAccountRoleRolloutSummary {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleRolloutSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleSpec) DeepCopyInto(out *AWSServiceAccountRoleSpec) {
	*out = *in
	out.ServiceAccount = in.ServiceAccount
	if in.PolicyARNs != nil {
		in, out := &in.PolicyARNs, &out.PolicyARNs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicyDocument != nil {
		in, out := &in.PolicyDocument, &out.PolicyDocument
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleSpec.
func (in *AWSServiceAccountRoleSpec) DeepCopy() *AWSServiceAccountRoleSpec {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleStatus) DeepCopyInto(out *AWSServiceAccountRoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ACKResources != nil {
		in, out := &in.ACKResources, &out.ACKResources
		*out = make([]ACKResourceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleStatus.
func (in *AWSServiceAccountRoleStatus) DeepCopy() *AWSServiceAccountRoleStatus {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSServiceAccountRoleTemplate) DeepCopyInto(out *AWSServiceAccountRoleTemplate) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(TemplateMetadata)
		(*in).DeepCopyInto(*out)
	}
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSServiceAccountRoleTemplate.
func (in *AWSServiceAccountRoleTemplate) DeepCopy() *AWSServiceAccountRoleTemplate {
	if in == nil {
		return nil
	}
	out := new(AWSServiceAccountRoleTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityConfig) DeepCopyInto(out *AWSWorkloadIdentityConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityConfig.
func (in *AWSWorkloadIdentityConfig) DeepCopy() *AWSWorkloadIdentityConfig {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSWorkloadIdentityConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityConfigList) DeepCopyInto(out *AWSWorkloadIdentityConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSWorkloadIdentityConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityConfigList.
func (in *AWSWorkloadIdentityConfigList) DeepCopy() *AWSWorkloadIdentityConfigList {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSWorkloadIdentityConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityConfigSpec) DeepCopyInto(out *AWSWorkloadIdentityConfigSpec) {
	*out = *in
	if in.EKSIRSA != nil {
		in, out := &in.EKSIRSA, &out.EKSIRSA
		*out = new(EKSIRSAConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityConfigSpec.
func (in *AWSWorkloadIdentityConfigSpec) DeepCopy() *AWSWorkloadIdentityConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityConfigStatus) DeepCopyInto(out *AWSWorkloadIdentityConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ACKResources != nil {
		in, out := &in.ACKResources, &out.ACKResources
		*out = make([]ACKResourceStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SelfHostedIssuer != nil {
		in, out := &in.SelfHostedIssuer, &out.SelfHostedIssuer
		*out = new(AWSWorkloadIdentityConfigSelfHostedIssuerStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.WebhookRuntimeCertNotAfter != nil {
		in, out := &in.WebhookRuntimeCertNotAfter, &out.WebhookRuntimeCertNotAfter
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityConfigStatus.
func (in *AWSWorkloadIdentityConfigStatus) DeepCopy() *AWSWorkloadIdentityConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityConfigSelfHostedIssuerPublicationStatus) DeepCopyInto(out *AWSWorkloadIdentityConfigSelfHostedIssuerPublicationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityConfigSelfHostedIssuerPublicationStatus.
func (in *AWSWorkloadIdentityConfigSelfHostedIssuerPublicationStatus) DeepCopy() *AWSWorkloadIdentityConfigSelfHostedIssuerPublicationStatus {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityConfigSelfHostedIssuerPublicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityConfigSelfHostedIssuerStatus) DeepCopyInto(out *AWSWorkloadIdentityConfigSelfHostedIssuerStatus) {
	*out = *in
	if in.Publication != nil {
		in, out := &in.Publication, &out.Publication
		*out = new(AWSWorkloadIdentityConfigSelfHostedIssuerPublicationStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityConfigSelfHostedIssuerStatus.
func (in *AWSWorkloadIdentityConfigSelfHostedIssuerStatus) DeepCopy() *AWSWorkloadIdentityConfigSelfHostedIssuerStatus {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityConfigSelfHostedIssuerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityOperatorConfig) DeepCopyInto(out *AWSWorkloadIdentityOperatorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityOperatorConfig.
func (in *AWSWorkloadIdentityOperatorConfig) DeepCopy() *AWSWorkloadIdentityOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSWorkloadIdentityOperatorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityOperatorConfigList) DeepCopyInto(out *AWSWorkloadIdentityOperatorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSWorkloadIdentityOperatorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityOperatorConfigList.
func (in *AWSWorkloadIdentityOperatorConfigList) DeepCopy() *AWSWorkloadIdentityOperatorConfigList {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityOperatorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSWorkloadIdentityOperatorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSWorkloadIdentityOperatorConfigSpec) DeepCopyInto(out *AWSWorkloadIdentityOperatorConfigSpec) {
	*out = *in
	out.SelfHostedIRSA = in.SelfHostedIRSA
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSWorkloadIdentityOperatorConfigSpec.
func (in *AWSWorkloadIdentityOperatorConfigSpec) DeepCopy() *AWSWorkloadIdentityOperatorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AWSWorkloadIdentityOperatorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSIRSAConfig) DeepCopyInto(out *EKSIRSAConfig) {
	*out = *in
	out.OIDCProvider = in.OIDCProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSIRSAConfig.
func (in *EKSIRSAConfig) DeepCopy() *EKSIRSAConfig {
	if in == nil {
		return nil
	}
	out := new(EKSIRSAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSIRSAOIDCProviderConfig) DeepCopyInto(out *EKSIRSAOIDCProviderConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSIRSAOIDCProviderConfig.
func (in *EKSIRSAOIDCProviderConfig) DeepCopy() *EKSIRSAOIDCProviderConfig {
	if in == nil {
		return nil
	}
	out := new(EKSIRSAOIDCProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementRef) DeepCopyInto(out *PlacementRef) {
	*out = *in
	in.RolloutStrategy.DeepCopyInto(&out.RolloutStrategy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementRef.
func (in *PlacementRef) DeepCopy() *PlacementRef {
	if in == nil {
		return nil
	}
	out := new(PlacementRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfHostedIRSAConfig) DeepCopyInto(out *SelfHostedIRSAConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfHostedIRSAConfig.
func (in *SelfHostedIRSAConfig) DeepCopy() *SelfHostedIRSAConfig {
	if in == nil {
		return nil
	}
	out := new(SelfHostedIRSAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountSubject) DeepCopyInto(out *ServiceAccountSubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountSubject.
func (in *ServiceAccountSubject) DeepCopy() *ServiceAccountSubject {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateMetadata) DeepCopyInto(out *TemplateMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]KubernetesLabelValue, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateMetadata.
func (in *TemplateMetadata) DeepCopy() *TemplateMetadata {
	if in == nil {
		return nil
	}
	out := new(TemplateMetadata)
	in.DeepCopyInto(out)
	return out
}
