name: Helm Chart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout operator
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4

      - name: Lint default values
        run: helm lint charts/aws-workload-identity-operator

      - name: Lint test values
        run: helm lint charts/aws-workload-identity-operator --values charts/aws-workload-identity-operator/values.test.yaml

      - name: Template default values
        run: |
          helm template aws-workload-identity-operator charts/aws-workload-identity-operator \
            --namespace aws-workload-identity-operator-system \
            --hide-notes >/tmp/aws-workload-identity-operator-default.yaml

      - name: Template test values
        run: |
          helm template aws-workload-identity-operator charts/aws-workload-identity-operator \
            --namespace aws-workload-identity-operator-system \
            --values charts/aws-workload-identity-operator/values.test.yaml \
            --hide-notes >/tmp/aws-workload-identity-operator-test.yaml

      - name: Package chart
        run: helm package charts/aws-workload-identity-operator --destination /tmp/charts
